Repository C0casio45/bot_onet, pull requests merged in 2022-05, with the labels that each got.

#30 Feature/faceit api
  bot.js
  bot_modules/faceit.js
  commands/ban.js
Labels: enhancement

#35 :rotating_light: Deleting old parameter
  commands/utils/embeds/request_userlink.js
Labels: FIX

#36 Feature/faceit api
  bot_modules/faceit.js
  button/mp_loop_close.js
  commands/ban.js
  commands/utils/embeds/result_error.js
  commands/utils/embeds/result_success.js
Labels: ENHANCEMENT

#40 Feature/auto unban
  bot_modules/faceit.js
  bot_modules/sendFunction.js
  commands/close.js
Labels: ENHANCEMENT

#41 Feature/auto unban
  bot.js
  bot_modules/faceit.js
  bot_modules/sendFunction.js
Labels: ENHANCEMENT

#43 :pencil2: Adding netinq to monitor
  bot_modules/monitor.js
Labels: ENHANCEMENT

#44 Dev
  bot_modules/monitor.js
Labels: ENHANCEMENT

#45 :fire: Fixing async issue
  bot_modules/monitor.js
Labels: ENHANCEMENT

#52 Enhancment/may
  bot.js
  bot_modules/CloseTicketAuto.js
  bot_modules/closeFunction.js
  bot_modules/deploy.js
  bot_modules/rappelUnban.js
  bot_modules/sendFunction.js
  bot_modules/unbanFunction.js
  button/setpage.js
  button/unban.js
  commands/ban.js
  commands/close.js
  commands/help.js
  commands/send.js
  commands/stats copy.js
  commands/stats.js
  commands/take.js
  commands/unban.js
  commands/utils/embeds/error.js
  commands/utils/embeds/request_gameLink.js
  commands/utils/embeds/request_mp.js
  commands/utils/embeds/request_other.js
  commands/utils/embeds/request_raison.js
  commands/utils/embeds/request_userdays.js
  commands/utils/embeds/request_userlink.js
  commands/utils/embeds/result_error.js
  commands/utils/embeds/result_success.js
  commands/utils/embeds/send_ban.js
  utils/buttons/mp_loop_buttons.js
  utils/buttons/mp_sanction_buttons.js
  utils/db/dbFactory.js
  utils/db/dbLibrary.js
  utils/embeds/EmbedMessageFactory.js
  utils/embeds/MessagesLibrary.js
Labels: ENHANCEMENT

#54 :art: Improve files name & functions name
  bot_modules/unban.js
  button/deprecatedUnban.js
  button/mpLoopClose.js
  button/mpLoopContinue.js
  button/mpResponseAvertissement.js
  button/mpResponsePerm.js
  button/unban.js
  commands/ban.js
  utils/buttons/mpLoop.js
  utils/buttons/mpSanction.js
Labels: ENHANCEMENT

#56 :bug: Fixing fetch error
  bot_modules/monitor.js
Labels: FIX

#66 Fix/ban
  bot_modules/faceit.js
  commands/ban.js
  utils/embeds/EmbedMessageFactory.js
  utils/embeds/MessagesLibrary.js
Labels: FIX

#70 :sparkles: Permit to take in every channel
  commands/take.js
Labels: ENHANCEMENT

#74 Feature/ban test
  .gitignore
  bot.js
  bot_modules/deploy.js
  bot_modules/faceit.js
  bot_modules/monitor.js
  bot_modules/rappelUnban.js
  button/emptyUrl.js
  button/mpLoopClose.js
  commands/ban.js
  commands/banTest.js
  commands/close.js
  logs.txt
  utils/buttons/mpGameUrl.js
  utils/embeds/EmbedMessageFactory.js
  utils/embeds/MessagesLibrary.js
Labels: ENHANCEMENT, FIX
